version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"